[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "2018"
name = "LC_API"
description = "Multipurpose modding API for Lethal Company"
websiteUrl = "https://github.com/steven4547466/LC-API"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "icons/icon.png"
readme = "../README.md"
outdir = "../dist"

[[build.copy]]
source = "../LC-API/bin/netstandard2.1/LC_API.dll"
target = "BepInEx/plugins/LC_API.dll"

[[build.copy]]
source = "./bundles"
target = "BepInEx/plugins/Bundles/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "../LICENSE"
target = "LICENSE"

[publish]
communities = ["lethal-company"]

[publish.categories]
lethal-company = ["bepinex", "libraries", "tools"]